services:
  - type: web
    name: oceanai
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn main:app -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: oceanai-db
          property: connectionString

databases:
  - name: oceanai-db
    databaseName: oceanai
    user: oceanai_user
